<a href="https://colab.research.google.com/github/sb0611sb/2026BDA/blob/main/w03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.ndarray((2,3))
a

array([[2.95570638e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [5]:
a = np.ndarray((2,3), dtype=int)
a

array([[605098916,         0,         0],
       [        0,         0,         0]])

In [6]:
a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [7]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)

(3,)
1
3
8


In [9]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.linspace(2,3,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [12]:
np.linspace(2,3,endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [16]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [17]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [21]:
a = np.arange(8).reshape(2,4)
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [24]:
a = np.arange(1,7).reshape(2,3)
b= np.full_like(a,[1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [27]:
a = np.full((2,3),[1,2,3])
b = np.full((3,2),[2,1])
print(a@b)
print(a.dot(b))
print(b.dot(a))
print(np.matmul(a,b))

[[12  6]
 [12  6]]
[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]
[[12  6]
 [12  6]]


In [29]:
a= np.array([[10,20],[5,8],[1,2]])
a.sum()

np.int64(46)

In [30]:
a.sum(axis=0)

array([16, 30])

In [31]:
a.sum(axis=1)

array([30, 13,  3])

In [32]:
a.cumsum()

array([10, 30, 35, 43, 44, 46])

In [33]:
a.cumsum(axis=0)

array([[10, 20],
       [15, 28],
       [16, 30]])

In [34]:
a.cumsum(axis=1)

array([[10, 30],
       [ 5, 13],
       [ 1,  3]])

In [37]:
a= np.array(np.arange(10))
print(a[3])
print(a[-2])
print(a[1:4])
print(a[-5:-1])
print(a[::-1])

3
8
[1 2 3]
[5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]


In [38]:
a[2:5] = 100
a

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [39]:
a = np.arange(12).reshape(3,4)
print(a[1])
print(a[-2,:])
print(a[-2,])

[4 5 6 7]
[4 5 6 7]
[4 5 6 7]


In [40]:
a = np.arange(24).reshape(2,3,4)
print(a[1])
print(a[:,-1])
print(a[:,1,1])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 8  9 10 11]
 [20 21 22 23]]
[ 5 17]


In [41]:
print(a[...,1])
print(a[1,...,1])
print(a[0,...])

[[ 1  5  9]
 [13 17 21]]
[13 17 21]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [48]:
lst[3:5] = [30,40,50]
lst

[0, 1, 2, 30, 40, 50, 50, 5, 6, 7]

In [49]:
x= np.arange(8)
x[3:5] = [30,40]
x


array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [51]:
a= np.array([[1,2,3],[4,5,6]])
b=a

In [53]:
print(id(a))
print(id(b))

133324795019056
133324795019056


In [54]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [55]:
c=a.copy()
print(id(a))
print(id(c))

133324795019056
133324794793584


In [56]:
a = np.array([3,4,5])
b = np.array([8,7,6])
a+b

array([11, 11, 11])

In [58]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(-1,2)


In [59]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [62]:
x = np.array([0,10,20,30])
a = x[None:]
a

array([ 0, 10, 20, 30])

In [65]:
b = x[:,None]
b

array([[ 0],
       [10],
       [20],
       [30]])

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [68]:
print(x[[2]])
print(x[[[2,3]]])

[2]
[[2 3]]


In [70]:
x = np.arange(12).reshape(3,4)
print(x[0])
print(x[:,2:8])

[0 1 2 3]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [71]:
print(x[[0],[1]])
print(x[[0,1]])

[1]
[[0 1 2 3]
 [4 5 6 7]]


In [74]:
x[[2,1],[2,2]]

array([10,  6])