<a href="https://colab.research.google.com/github/sb0611sb/2026BDA/blob/main/w04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a= np.arange(6).reshape(3,2)
b= np.arange(6,12).reshape(3,2)

np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,15).reshape(3,3)
np.hstack((a,b))

array([[ 0,  1,  6,  7,  8],
       [ 2,  3,  9, 10, 11],
       [ 4,  5, 12, 13, 14]])

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
a=np.array([1,2])
b=np.array([1,2])
c=np.array([1,2])

np.concatenate([a,b,c])

array([1, 2, 1, 2, 1, 2])

In [9]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
c=np.arange(12,16).reshape(2,2)

print(np.concatenate((a,b),axis=1))
np.concatenate((a,b,c),axis=1)


[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


array([[ 0,  1,  2,  6,  7,  8, 12, 13],
       [ 3,  4,  5,  9, 10, 11, 14, 15]])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.stack((a,b)))
print(np.stack((a,b),axis=-1))
print(np.stack((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [16]:
a=np.arange(6).reshape(2,3)
b=np.arange(10,16).reshape(2,3)
c=np.arange(20,26).reshape(2,3)

print(np.stack((a,b,c),axis=0))
print(np.stack((a,b,c),axis=1))
print(np.stack((a,b,c),axis=2))

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.c_[a,b]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])

print(np.c_[a,10,20,b])
print(np.column_stack((a,10,20,b)))

[[ 1  2  3 10 20  4  5  6]]
[[ 1  2  3 10 20  4  5  6]]


In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.r_[a,b])
print(np.r_[a,-1,0,b])
print(np.r_[3:10:3,[0]*2,5,6])
print(np.r_[3:10:3j,[0]*2,5,6])


[1 2 3 4 5 6]
[ 1  2  3 -1  0  4  5  6]
[3 6 9 0 0 5 6]
[ 3.   6.5 10.   0.   0.   5.   6. ]


In [27]:
a=np.array([[1,2,3],[4,5,6]])

print(np.r_[a,a,a])
print(np.r_['0',a,a])
print(np.r_['1',a,a])
print(np.r_['-1',a,a])

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [28]:
a=np.arange(9.0)
np.split(a,3)


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [29]:
a=np.arange(24).reshape(2,12)
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [31]:
a=np.arange(10)
print(np.hsplit(a,2))
print(np.hsplit(a,[2,5]))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]


[array([0, 1, 2]), array([3, 4]), array([5, 6, 7]), array([8, 9])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(np.vsplit(a,2))

In [33]:
a=np.arange(32).reshape(4,4,2)
np.vsplit(a,[1,3])
print(a[:1,:,:])
print(a[1:3])
print(a[3:])

[[[0 1]
  [2 3]
  [4 5]
  [6 7]]]
[[[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[24 25]
  [26 27]
  [28 29]
  [30 31]]]


In [34]:
a=np.arange(32).reshape(4,4,2)
np.hsplit(a,[1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [35]:
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x7A709C44D7E0

In [37]:
print(rg.random())
print(rg.random(5))
print(rg.random((2,3)))

0.8277025938204418
[0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
[[0.32973172 0.7884287  0.30319483]
 [0.45349789 0.1340417  0.40311299]]


In [38]:
print(rg.integers(low=1,high=10,size=2))
print(rg.integers(1,7,(3,4)))

[9 2]
[[4 2 1 5]
 [1 2 3 3]
 [1 6 5 6]]


In [39]:
print(rg.standard_normal(10))
print(rg.standard_normal((4,3)))

[-1.88901325 -0.17477209 -0.42219041  0.213643    0.21732193  2.11783876
 -1.11202076 -0.37760501  2.04277161  0.646703  ]
[[ 0.66306337 -0.51400637 -1.64807517]
 [ 0.16746474  0.10901409 -1.22735205]
 [-0.68322666 -0.07204368 -0.94475162]
 [-0.09826997  0.09548303  0.03558624]]
